# Site
name: 'Controlled Mold'
description: 'A blog about fermentation, food science, and urban cellular agriculture.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
email: 'cam.davidson.pilon@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    cam:
      name:           Cameron Davidson-Pilon
      site:           https://dataorigami.net/
      avatar:         /assets/images/camdp.jpg
      bio:            'Bad statistician turned even worse food scientist.


Cameron''s background includes mathematics, statistics, computer science and spending a lot of time
thinking about ecommerce at Shopify. He is the author of "Bayesian Methods for Hackers". Cameron later pivoted into food science and now explores the alt-protein space.'

      email:          cam.davidson.pilon@gmail.com
      twitter:        https://www.twitter.com/cmrn_dp


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: cam
      avatar: /assets/images/camdp.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]