# Site
name: 'Controlled Mold'
description: 'A blog about fermentation, data science, and cell-ag'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
email: 'cam.davidson.pilon@gmail.com'
disqus: controlledmold
include: ["_pages"]
permalink: /:title/
url: https://controlledmold.com
enforce_ssl: ccontrolledmold.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

authors:
    cam:
      name:           Cameron Davidson-Pilon
      site:           https://dataorigami.net/
      avatar:         /assets/images/authors/camdp.jpg
      bio:            'Bad statistician turned even worse food scientist. Former Director of Data Science at Shopify.


Cameron''s background includes mathematics, statistics, and computer science (topics blogged at <a href="https://dataorigami.net/">dataorigami.net</a>). He is the author of <a href="https://www.amazon.ca/Bayesian-Methods-Hackers-Probabilistic-Programming/dp/0133902838">"Bayesian Methods for Hackers"</a>. Cameron now explores the alt-protein space.'

      email:          cam.davidson.pilon@gmail.com
      twitter:        https://www.twitter.com/cmrn_dp
      linkedin:       https://www.linkedin.com/in/cameron-davidson-pilon-708b5340/
      github:         https://github.com/camDavidsonPilon


    keith:
      name: Keith Wong
      avatar: /assets/images/authors/Keith.jpg
      bio: 'Chemical engineer and fermentation hobbyist with a background in wastewater, drinking water, and solid waste management. Keith enjoys natto and anything koji-related.'
      linkedin: https://www.linkedin.com/in/keith-wong-a032408a/
      twitter: https://twitter.com/Keeifa
      github: https://github.com/daizu27


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: cam
      avatar: /assets/images/camdp.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
